

export const GET_ALL_DRONE_STRIKES = 'GET_ALL_DRONE_STRIKES';
export const GET_SPECIFIC_DRONE_STRIKE = 'GET_SPECIFIC_DRONE_STRIKE';


export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER_LOGIN_STATUS = 'SET_USER_LOGIN_STATUS';


export const GET_LOADING_STATUS = 'GET_LOADING_STATUS';
export const GET_ERROR_STATUS = 'GET_ERROR_STATUS';
export const GET_TOGGLE_STATUS = 'GET_TOGGLE_STATUS';